// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `fileformat.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct Blob {
    // message fields
    raw_size: ::std::option::Option<i32>,
    // message oneof groups
    pub data: ::std::option::Option<Blob_oneof_data>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Blob {
    fn default() -> &'a Blob {
        <Blob as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum Blob_oneof_data {
    raw(::std::vec::Vec<u8>),
    zlib_data(::std::vec::Vec<u8>),
    lzma_data(::std::vec::Vec<u8>),
    OBSOLETE_bzip2_data(::std::vec::Vec<u8>),
    lz4_data(::std::vec::Vec<u8>),
    zstd_data(::std::vec::Vec<u8>),
}

impl Blob {
    pub fn new() -> Blob {
        ::std::default::Default::default()
    }

    // optional int32 raw_size = 2;


    pub fn get_raw_size(&self) -> i32 {
        self.raw_size.unwrap_or(0)
    }
    pub fn clear_raw_size(&mut self) {
        self.raw_size = ::std::option::Option::None;
    }

    pub fn has_raw_size(&self) -> bool {
        self.raw_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_raw_size(&mut self, v: i32) {
        self.raw_size = ::std::option::Option::Some(v);
    }

    // optional bytes raw = 1;


    pub fn get_raw(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::raw(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_raw(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_raw(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::raw(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_raw(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::raw(v))
    }

    // Mutable pointer to the field.
    pub fn mut_raw(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::raw(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::raw(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::raw(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_raw(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_raw() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::raw(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // optional bytes zlib_data = 3;


    pub fn get_zlib_data(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zlib_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_zlib_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_zlib_data(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zlib_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_zlib_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::zlib_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_zlib_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::zlib_data(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::zlib_data(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zlib_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_zlib_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_zlib_data() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::zlib_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // optional bytes lzma_data = 4;


    pub fn get_lzma_data(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lzma_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_lzma_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_lzma_data(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lzma_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_lzma_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::lzma_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_lzma_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::lzma_data(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::lzma_data(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lzma_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_lzma_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_lzma_data() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::lzma_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // optional bytes OBSOLETE_bzip2_data = 5;


    pub fn get_OBSOLETE_bzip2_data(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_OBSOLETE_bzip2_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_OBSOLETE_bzip2_data(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_OBSOLETE_bzip2_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_OBSOLETE_bzip2_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_OBSOLETE_bzip2_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_OBSOLETE_bzip2_data() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // optional bytes lz4_data = 6;


    pub fn get_lz4_data(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lz4_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_lz4_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_lz4_data(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lz4_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_lz4_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::lz4_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_lz4_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::lz4_data(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::lz4_data(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::lz4_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_lz4_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_lz4_data() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::lz4_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // optional bytes zstd_data = 7;


    pub fn get_zstd_data(&self) -> &[u8] {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zstd_data(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_zstd_data(&mut self) {
        self.data = ::std::option::Option::None;
    }

    pub fn has_zstd_data(&self) -> bool {
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zstd_data(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_zstd_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = ::std::option::Option::Some(Blob_oneof_data::zstd_data(v))
    }

    // Mutable pointer to the field.
    pub fn mut_zstd_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(Blob_oneof_data::zstd_data(_)) = self.data {
        } else {
            self.data = ::std::option::Option::Some(Blob_oneof_data::zstd_data(::std::vec::Vec::new()));
        }
        match self.data {
            ::std::option::Option::Some(Blob_oneof_data::zstd_data(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_zstd_data(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_zstd_data() {
            match self.data.take() {
                ::std::option::Option::Some(Blob_oneof_data::zstd_data(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }
}

impl ::protobuf::Message for Blob {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.raw_size = ::std::option::Option::Some(tmp);
                },
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::raw(is.read_bytes()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::zlib_data(is.read_bytes()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::lzma_data(is.read_bytes()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::OBSOLETE_bzip2_data(is.read_bytes()?));
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::lz4_data(is.read_bytes()?));
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.data = ::std::option::Option::Some(Blob_oneof_data::zstd_data(is.read_bytes()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.raw_size {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let ::std::option::Option::Some(ref v) = self.data {
            match v {
                &Blob_oneof_data::raw(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(1, &v);
                },
                &Blob_oneof_data::zlib_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(3, &v);
                },
                &Blob_oneof_data::lzma_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(4, &v);
                },
                &Blob_oneof_data::OBSOLETE_bzip2_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(5, &v);
                },
                &Blob_oneof_data::lz4_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(6, &v);
                },
                &Blob_oneof_data::zstd_data(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(7, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.raw_size {
            os.write_int32(2, v)?;
        }
        if let ::std::option::Option::Some(ref v) = self.data {
            match v {
                &Blob_oneof_data::raw(ref v) => {
                    os.write_bytes(1, v)?;
                },
                &Blob_oneof_data::zlib_data(ref v) => {
                    os.write_bytes(3, v)?;
                },
                &Blob_oneof_data::lzma_data(ref v) => {
                    os.write_bytes(4, v)?;
                },
                &Blob_oneof_data::OBSOLETE_bzip2_data(ref v) => {
                    os.write_bytes(5, v)?;
                },
                &Blob_oneof_data::lz4_data(ref v) => {
                    os.write_bytes(6, v)?;
                },
                &Blob_oneof_data::zstd_data(ref v) => {
                    os.write_bytes(7, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Blob {
        Blob::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "raw_size",
                |m: &Blob| { &m.raw_size },
                |m: &mut Blob| { &mut m.raw_size },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "raw",
                Blob::has_raw,
                Blob::get_raw,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "zlib_data",
                Blob::has_zlib_data,
                Blob::get_zlib_data,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "lzma_data",
                Blob::has_lzma_data,
                Blob::get_lzma_data,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "OBSOLETE_bzip2_data",
                Blob::has_OBSOLETE_bzip2_data,
                Blob::get_OBSOLETE_bzip2_data,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "lz4_data",
                Blob::has_lz4_data,
                Blob::get_lz4_data,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "zstd_data",
                Blob::has_zstd_data,
                Blob::get_zstd_data,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Blob>(
                "Blob",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Blob {
        static instance: ::protobuf::rt::LazyV2<Blob> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Blob::new)
    }
}

impl ::protobuf::Clear for Blob {
    fn clear(&mut self) {
        self.raw_size = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.data = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Blob {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Blob {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BlobHeader {
    // message fields
    field_type: ::protobuf::SingularField<::std::string::String>,
    indexdata: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    datasize: ::std::option::Option<i32>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BlobHeader {
    fn default() -> &'a BlobHeader {
        <BlobHeader as ::protobuf::Message>::default_instance()
    }
}

impl BlobHeader {
    pub fn new() -> BlobHeader {
        ::std::default::Default::default()
    }

    // required string type = 1;


    pub fn get_field_type(&self) -> &str {
        match self.field_type.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_field_type(&mut self) {
        self.field_type.clear();
    }

    pub fn has_field_type(&self) -> bool {
        self.field_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: ::std::string::String) {
        self.field_type = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_field_type(&mut self) -> &mut ::std::string::String {
        if self.field_type.is_none() {
            self.field_type.set_default();
        }
        self.field_type.as_mut().unwrap()
    }

    // Take field
    pub fn take_field_type(&mut self) -> ::std::string::String {
        self.field_type.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional bytes indexdata = 2;


    pub fn get_indexdata(&self) -> &[u8] {
        match self.indexdata.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_indexdata(&mut self) {
        self.indexdata.clear();
    }

    pub fn has_indexdata(&self) -> bool {
        self.indexdata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_indexdata(&mut self, v: ::std::vec::Vec<u8>) {
        self.indexdata = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_indexdata(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.indexdata.is_none() {
            self.indexdata.set_default();
        }
        self.indexdata.as_mut().unwrap()
    }

    // Take field
    pub fn take_indexdata(&mut self) -> ::std::vec::Vec<u8> {
        self.indexdata.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // required int32 datasize = 3;


    pub fn get_datasize(&self) -> i32 {
        self.datasize.unwrap_or(0)
    }
    pub fn clear_datasize(&mut self) {
        self.datasize = ::std::option::Option::None;
    }

    pub fn has_datasize(&self) -> bool {
        self.datasize.is_some()
    }

    // Param is passed by value, moved
    pub fn set_datasize(&mut self, v: i32) {
        self.datasize = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for BlobHeader {
    fn is_initialized(&self) -> bool {
        if self.field_type.is_none() {
            return false;
        }
        if self.datasize.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.field_type)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.indexdata)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.datasize = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.field_type.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.indexdata.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        if let Some(v) = self.datasize {
            my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.field_type.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.indexdata.as_ref() {
            os.write_bytes(2, &v)?;
        }
        if let Some(v) = self.datasize {
            os.write_int32(3, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BlobHeader {
        BlobHeader::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "type",
                |m: &BlobHeader| { &m.field_type },
                |m: &mut BlobHeader| { &mut m.field_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "indexdata",
                |m: &BlobHeader| { &m.indexdata },
                |m: &mut BlobHeader| { &mut m.indexdata },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "datasize",
                |m: &BlobHeader| { &m.datasize },
                |m: &mut BlobHeader| { &mut m.datasize },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BlobHeader>(
                "BlobHeader",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BlobHeader {
        static instance: ::protobuf::rt::LazyV2<BlobHeader> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BlobHeader::new)
    }
}

impl ::protobuf::Clear for BlobHeader {
    fn clear(&mut self) {
        self.field_type.clear();
        self.indexdata.clear();
        self.datasize = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BlobHeader {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlobHeader {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10fileformat.proto\x12\x06OSMPBF\"\xfb\x01\n\x04Blob\x12\x1b\n\x08ra\
    w_size\x18\x02\x20\x01(\x05R\x07rawSizeB\0\x12\x14\n\x03raw\x18\x01\x20\
    \x01(\x0cH\0R\x03rawB\0\x12\x1f\n\tzlib_data\x18\x03\x20\x01(\x0cH\0R\
    \x08zlibDataB\0\x12\x1f\n\tlzma_data\x18\x04\x20\x01(\x0cH\0R\x08lzmaDat\
    aB\0\x124\n\x13OBSOLETE_bzip2_data\x18\x05\x20\x01(\x0cH\0R\x11OBSOLETEB\
    zip2DataB\x02\x18\x01\x12\x1d\n\x08lz4_data\x18\x06\x20\x01(\x0cH\0R\x07\
    lz4DataB\0\x12\x1f\n\tzstd_data\x18\x07\x20\x01(\x0cH\0R\x08zstdDataB\0B\
    \x06\n\x04data:\0\"b\n\nBlobHeader\x12\x14\n\x04type\x18\x01\x20\x02(\tR\
    \x04typeB\0\x12\x1e\n\tindexdata\x18\x02\x20\x01(\x0cR\tindexdataB\0\x12\
    \x1c\n\x08datasize\x18\x03\x20\x02(\x05R\x08datasizeB\0:\0B\0b\x06proto2\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
