name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '17 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v3
      - name: Print versions
        run: rustc -V && cargo -V
      - name: Ensure code format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests (with zlib)
        run: cargo test --verbose --no-default-features --features zlib
      - name: Run tests (with zlib-ng)
        run: cargo test --verbose --no-default-features --features zlib-ng
      - name: Lint
        run: cargo clippy -- -Dwarnings
      - name: Build documentation
        run: cargo doc --verbose

  TestMatrix:
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      matrix:
        # We test using the latest stable and MSRV Rust versions.
        rust_version: ["stable", "1.74.1"]
        runs_on: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: "${{ matrix.runs_on }}"
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "${{ matrix.rust_version }}"
          override: true
          profile: minimal
      - run: cargo test
