name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '17 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v3
      - name: Ensure code format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests (no default features)
        run: cargo test --verbose --no-default-features
      - name: Lint
        run: cargo clippy -- -Dwarnings
      - name: Build documentation
        run: cargo doc --verbose

  TestMatrix:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      matrix: 
        # Which Rust versions to test - latest and MSRV should be enough for now. 
        rust_version: ["1.62.0", "1.58.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "${{ matrix.rust_version }}"
          override: true
          profile: minimal
      - run: cargo test
